name: Daily Series Scraping

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Manually triggerable workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Use the appropriate PHP version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        sudo mv composer.phar /usr/local/bin/composer

    - name: Install required PHP extensions
      run: |
        sudo apt-get install -y php-curl php-mbstring php-xml

    - name: Run the PHP Script
      run: |
        php scrape_series.php

    - name: Commit and push changes (if new data is available)
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        
        git add .
        git diff --exit-code || git commit -m "Update series data: $(date +'%Y-%m-%d')"
        
        # Only push if there are changes (new series or episodes)
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
